{
 "title": "Service Dashboards",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(assisted_migration_inventory_customers_total,pod)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "# No of customers",
   "type": "text",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
   "options": {
    "content": "Number total of customers including those without any assestements."
   }
  },
  {
   "title": "No of customers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n  count by (customer) (\n    sum by (customer, source_type) (\n  # Group A: org_id is numeric OR \"redhat.com\"\n  label_replace(\n    assisted_migration_inventory_total_assessments_by_customer_by_source_type{\n      service=\"migration-planner-metrics\",\n      org_id=~\"^[0-9]+$|^redhat.com$\"\n    },\n    \"customer\",\n    \"redhat.com\",\n    \"org_id\",\n    \".*\"\n  )\n  OR\n  # Group B: non-numeric, not redhat.com, not empty, not 'example'\n  label_replace(\n    assisted_migration_inventory_total_assessments_by_customer_by_source_type{\n      service=\"migration-planner-metrics\",\n      org_id!~\"^[0-9]+$|^redhat.com$|^$|^example$\"\n    },\n    \"customer\",\n    \"$1\",\n    \"org_id\",\n    \"^(.*)$\"\n  )\n  ) / 3\n))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Unique visitors per week",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 14, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "max(assisted_migration_visits_count_per_week)",
     "legendFormat": "Visits"
    }
   ]
  },
  {
   "title": "# No of vms",
   "type": "text",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 6 },
   "options": {
    "content": "Total number of vm of all customers."
   }
  },
  {
   "title": "No of VMs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 5, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (service) (assisted_migration_inventory_vms_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "# No of assessments",
   "type": "text",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 11 },
   "options": {
    "content": "Number total of assessments including the assessments without any inventory."
   }
  },
  {
   "title": "No of assessments",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 5, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (service) (assisted_migration_inventory_total_assessments_by_customer_by_source_type{service=\"migration-planner-metrics\"}) / 3",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Temp OVA directory size",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 8, "y": 11 },
   "targets": [
    {
     "expr": "assisted_migration_directory_size_temp_ova_directory",
     "legendFormat": "GB"
    }
   ]
  },
  {
   "title": "Total number of assessments per organization & source type",
   "type": "table",
   "gridPos": { "h": 10, "w": 7, "x": 15, "y": 11 },
   "targets": [
    {
     "expr": "sum by (org_id, source_type) (\n    assisted_migration_inventory_total_assessments_by_customer_by_source_type{\n      service=\"migration-planner-metrics\",\n      org_id!~\"example.com|^$\"\n    }\n) / 3 > 0",
     "legendFormat": "{{customer}} - {{source_type}}"
    }
   ]
  },
  {
   "title": "# No of Operating System",
   "type": "text",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 16 },
   "options": {
    "content": "Number of distinct operating systems."
   }
  },
  {
   "title": "No of Operating Systems",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 5, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (group(assisted_migration_inventory_vms_by_os_total) by (os))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Top 5", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Top Operating Systems",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, sum by (os) (assisted_migration_inventory_vms_by_os_total) / 3)",
     "legendFormat": "{{os}}"
    }
   ]
  },
  {
   "title": "Top customers by number of VMs",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 7, "x": 8, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(6, sum by (org_id) (\n    assisted_migration_inventory_vms_by_customer_total{\n      service=\"migration-planner-metrics\",\n      org_id!~\"example.com|^$|example\"\n    }\n) / 3 \n)\n\n",
     "legendFormat": "{{org_id}}"
    }
   ]
  },
  {
   "title": "Top customers by total storage",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 7, "x": 15, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, sum by (org_id) (\n    assisted_migration_inventory_storage_by_customer_total{\n      service=\"migration-planner-metrics\",\n      org_id!~\"example.com|^$|example\",\n    }\n) / 3 \n)\n\n",
     "legendFormat": "{{org_id}}"
    }
   ]
  },
  { "title": "Ova download metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Total downloads in the last 5m",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (service) (increase(assisted_migration_ova_downloads_total{state=\"successful\", service=\"migration-planner-metrics\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ova downloads over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 34 },
   "targets": [
    {
     "expr": "sum by (state) (increase(assisted_migration_ova_downloads_total{}[1m]))",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Successfull downloads in the last 24h",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (state) (increase(assisted_migration_ova_downloads_total{state=\"successful\"}[24h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "VMs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "VMs by Operating System",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "sort_desc(sum by (os) (assisted_migration_inventory_vms_by_os_total{}) / 3)",
     "legendFormat": "{{os}}"
    }
   ]
  },
  {
   "title": "VMs by customer",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "expr": "sum by (customer) (\n  # Group A: org_id is numeric OR \"redhat.com\"\n  label_replace(\n    assisted_migration_inventory_vms_by_customer_total{\n      org_id=~\"^[0-9]+$|^redhat.com$\",\n    },\n    \"customer\",\n    \"redhat.com\",\n    \"org_id\",\n    \".*\"\n  )\n  OR\n  # Group B: everything else (non-numeric, not redhat.com, not empty, not 'example')\n  label_replace(\n    assisted_migration_inventory_vms_by_customer_total{\n      org_id!~\"^[0-9]+$|^redhat.com$|^$|^example$\"\n    },\n    \"customer\",\n    \"$1\",\n    \"org_id\",\n    \"^(.*)$\"\n  )\n) / 3 \n\n\n\n",
     "legendFormat": "{{org_id}}"
    }
   ]
  },
  {
   "title": "Storage by customer",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 54 },
   "targets": [
    {
     "expr": "max by (org_id, type) (\n    assisted_migration_inventory_storage_by_customer_total{\n      service=\"migration-planner-metrics\",\n      org_id!~\"example.com|^$|example\",\n    }\n)\n\n\n",
     "legendFormat": "{{org_id}}"
    }
   ]
  }
 ]
}